export const items = [
  {
    id: 1,
    category: "Dark Moon",
    banner: "./assets/images/showcase-7.jpg",
    avatar: "./assets/images/avatar-7.jpg",
    artist: "Yousef",
    title: "Dark Moon Token ",
    price: "0.5 ETH",
  },
  {
    id: 2,
    category: "Digital Shoes",
    banner: "./assets/images/showcase-3.jpg",
    avatar: "./assets/images/avatar-6.gif",
    artist: "Huthaifa",
    title: "Digtal Shoes ",
    price: "1.2 ETH",
  },
  {
    id: 3,
    category: "Alien Drinks",
    banner: "./assets/images/showcase-5.jpg",
    avatar: "./assets/images/avatar-5.jpg",
    artist: "Mohamed",
    title: "Alien Drinks",
    price: "2.8 ETH",
  },
  {
    id: 4,
    category: "Long Jacket Punks",
    banner: "./assets/images/showcase-4.jpg",
    avatar: "./assets/images/avatar-4.jpg",
    artist: "Ahmed",
    title: "Long Jacket Punks",
    price: "1.5 ETH",
  },
  {
    id: 5,
    category: "Quiet Quarry Runway",
    banner: "./assets/images/showcase-6.jpg",
    avatar: "./assets/images/avatar-3.jpg",
    artist: "Ali",
    title: "Quiet Quarry Runway",
    price: "0.8 ETH",
  },
  {
    id: 6,
    category: "ERA",
    banner: "./assets/images/showcase-8.gif",
    avatar: "./assets/images/avatar-8.jpg",
    artist: "Karam",
    title: "ERA ",
    price: "3.2 ETH",
  },
  {
    id: 7,
    category: "Alyxandra Common",
    banner: "./assets/images/showcase-2.jpg",
    avatar: "./assets/images/avatar-2.jpg",
    artist: "Omar",
    title: "Alyxandra Common",
    price: "1.9 ETH",
  },
  {
    id: 8,
    category: "Digital Fashion",
    banner: "./assets/images/showcase-1.jpg",
    avatar: "./assets/images/avatar-1.jpg",
    artist: "Abdullah",
    title: "Digtal Fashion ",
    price: "0.7 ETH",
  },
];
