export const items = [
  {
    id: 1,
    category: "Cryptocurrency",
    banner: "../src/assets/images/products/showcase-7.jpg",
    avatar: "../src/assets/images//avatar/avatar-7.jpg",
    artist: "Yousef",
    title: "Dark Moon Token ",
    price: 0.5,
  },
  {
    id: 2,
    category: "Footwear",
    banner: "../src/assets/images/products/showcase-3.jpg",
    avatar: "../src/assets/images/avatar/avatar-6.gif",
    artist: "Huthaifa",
    title: "Digtal Shoes ",
    price: 1.2,
  },
  {
    id: 3,
    category: "Beverages",
    banner: "../src/assets/images/products/showcase-5.jpg",
    avatar: "../src/assets/images/avatar/avatar-5.jpg",
    artist: "Mohamed",
    title: "Alien Drinks",
    price: 2.8,
  },
  {
    id: 4,
    category: "Outerwear",
    banner: "../src/assets/images/products/showcase-4.jpg",
    avatar: "../src/assets/images/avatar/avatar-4.jpg",
    artist: "Ahmed",
    title: "Long Jacket Punks",
    price: 1.5,
  },
  {
    id: 5,
    category: "Fashion",
    banner: "../src/assets/images/products/showcase-6.jpg",
    avatar: "../src/assets/images/avatar/avatar-3.jpg",
    artist: "Ali",
    title: "Quiet Quarry Runway",
    price: 0.8,
  },
  {
    id: 6,
    category: "Technology",
    banner: "../src/assets/images/products/showcase-8.gif",
    avatar: "../src/assets/images//avatar/avatar-8.jpg",
    artist: "Karam",
    title: "ERA Tech",
    price: 3.2,
  },
  {
    id: 7,
    category: "Clothing",
    banner: "../src/assets/images/products/showcase-2.jpg",
    avatar: "../src/assets/images/avatar/avatar-2.jpg",
    artist: "Omar",
    title: "Alyxandra Common",
    price: 1.9,
  },
  {
    id: 8,
    category: "Fashion/Tech",
    banner: "../src/assets/images/products/showcase-1.jpg",
    avatar: "../src/assets/images/avatar/avatar-1.jpg",
    artist: "Abdullah",
    title: "Digtal Fashion ",
    price: 0.7,
  },
];
